name:          CrossLink School of Best Practices
title:         CrossLink School of Best Practices
description:   Engineering best practices used by 10up.
url:           https://best-practices.cross-link.ch/
baseurl:       /
author:
  name:    CrossLink
  email:   help@cross.link
  github:  crosslink-ch
  twitter: 10up

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
